### ISSUE TITLE
HODL payment pending since 15 december 2023

### ISSUE THREAD

**Issue by lescuer97** [RoboSats/robosats#1058]
**Describe the bug**
I have a pending payment from a HODL invoice from a transaction that I created and canceled before someone took it. 

This happened using Mutiny wallet.

value of the transaction is: 38956 sats. 

don't know what other data you need to check this out.

**Comment by Reckless-Satoshi** [comment]
Hey @lescuer97 

It sounds this is something that has to do with the operation of the experimental coordinator rather than with the project codebase. The right approach is to write in one of the public support groups.

As far as I can tell, HODL invoices created by a robosats backend can't be in hold longer than ~48-96hours worst case (even if the whole backend goes offline). It is a limitation imposed by the routing nodes that would force close the channels and cancel the payment anyway. So this is most likely an issue on the wallet side.

Closing the issue.
