### ISSUE TITLE
Stuck on Sending satoshis to buyer Order status

### ISSUE THREAD

**Issue by disclosednym** [RoboSats/robosats#1128]
**Describe the bug**
Robosats is stuck on spinner trying to pay my lightning invoice. My lightning node is on (Pheonix) and I have adequate inbound liquidity.

**To Reproduce**
1. Go through order process.
2. If payout fails, change fees in advanced menu (e.g. 1,000 >10,000).
3. Stuck on spinner.

**Expected behavior**
Expected my payout to complete

**Screenshots**
![image](https://github.com/RoboSats/robosats/assets/159712053/414ec412-2689-4181-b778-968f68ecdfd8)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Firefox
 - 0.5.3

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android 14
 - Pheonix 
 

**Additional context**
Not sure where else to turn to, please help!

**Comment by Reckless-Satoshi** [comment]
A payout invoice can get stuck in that step when one of the payment parts is accepted and never released. Therefore the payment is neither succeeding or failing. This is extremely common with Phoenix. You need to wait for the payment to fail in order to retry. For more information or help if the payment is still stuck after ~48h, you will need to reach out to your RoboSats coordinator.

Closing this issue as it does not relate to the RoboSats codebase, but to Lightning Network quirks.

**Comment by disclosednym** [comment]
> A payout invoice can get stuck in that step when one of the payment parts is accepted and never released. Therefore the payment is neither succeeding or failing. This is extremely common with Phoenix. You need to wait for the payment to fail in order to retry. For more information or help if the payment is still stuck after ~48h, you will need to reach out to your RoboSats coordinator.
> 
> Closing this issue as it does not relate to the RoboSats codebase, but to Lightning Network quirks.

Thanks for your time on this. Could you tell me how to reachout to my robosats coordinator?
