### ISSUE TITLE
Incorrect Sats now for Swaps

### ISSUE THREAD

**Issue by santochibtc** [RoboSats/robosats#1201]
**Describe the bug**
The value shown in sats now for the swaps is incorrect.
In this example, the swap out with positive premium shows less "sats now" than the other swap with negative premium (a discount for the maker)
![imagen](https://github.com/RoboSats/robosats/assets/105021322/052540d6-3ce3-4187-87f2-782573ca9c7b)
If I want to swap in with a discount I have to set a negative premium 
![imagen](https://github.com/RoboSats/robosats/assets/105021322/57e1c65f-5b90-4e1a-802b-237b617cd41f)

**Comment by santochibtc** [comment]
Taking a swap order, the value of sats that I will receive is incorrect too
In this example, I want to swap in, I will send 1M on chain and will receive less LN sats because I have to pay the taker fee
![imagen](https://github.com/RoboSats/robosats/assets/105021322/1f79f86e-68c3-4b90-9ad7-536e2d57b288)

**Comment by Reckless-Satoshi** [comment]
Thank you for reporting. Yes, these two seem to be UI issues that must be solved.

The UI predicts the costs and amounts. These functions seem to be buggy. Even if the UI is wrong, the actual amounts if you do the trades will be exactly right because this bug is only on the client, the coordinator backend runs the numbers right.

**Comment by santochibtc** [comment]
Thank you! Yes, the final amounts always were correct

**Comment by nikkuAg** [comment]
Hey, is this issue still open? I would like to work on this
