### ISSUE TITLE
Stronger privacy for invoice descriptions

### ISSUE THREAD

**Issue by errornullvoid** [RoboSats/robosats#282]
[]

**Comment by Reckless-Satoshi** [comment]
Hey @tiddymasher that's a lot for bringing this concern and offering a hand!

Well, this discussion has already taken place, the work has been done and what you currently see live is the solution: see #168 and #210.

Stealth invoices are in fact now the default. Senders nodes will always know they are sending Sats to RoboSats, it is unavoidable: Bolt11 encodes for the Node ID of the receiver (RoboSats node). The current description is generic and does not add any new info that compromises the user. However it adds useful tips that are always nice for the new users and experienced alike.

We could discuss though "description-less" invoices. I am not sure there is any privacy gain for them... maybe your wife checking your phone screen while you scroll your transactions :smile:  (... a valid concern though!!)

**Comment by tiddymasher** [comment]
Yeah I understand at a certain point sender nodes can see where its going. I think my main point is to try and make it less obvious where possible with description-less invoices that way it isn't _immediately_ obvious. Currently, most employee of a KYC exchange could identify robosats users at a glance, however the inner details of a LN invoice transaction are typically only accessible through the team responsible for operating and maintaining the LN node. If I had to have a conversation with customer service for example, I wouldn't want them to be able to easily identify "oh, this is a robosats invoice based on the description" because honestly, its not really for them to know. 

It also sounds like maybe the best way to handle this if it is a concern would be to set up a node and open a private channel with Robosats - is that possible? Then the transaction flow could look something like use KYC exchange to fund node, and then use that node to pay invoices on Robosats.

Thanks for the links, I will check them out.

**Comment by Reckless-Satoshi** [comment]
> most employees of a KYC exchange could identify robosats users at a glance

True that. Though it rather depends on how they parse the invoice info. I would take for granted they also have a field with the Alias of the node the transition goes to and probably the route it took (all node alias  hop by hop). It might be key to debug / help customers.

Again, the only way to actually be private is to do your own routing (do not use that service, but your own node).

> It also sounds like maybe the best way to handle this if it is a concern would be to set up a node and open a private channel with Robosats - is that possible? 

Of course! But no need to go to that extend! One can use private wallets like Blixt or Phoenix (light mobile nodes). No direct channels with RoboSats are needed either. More info about wallets in https://learn.robosats.com/docs/wallets

**Comment by lnproxy** [comment]
Could be a good idea to recommend that users of custodial KYC wallets wrap robosats invoices before paying them so that their custodians are not able to figure out that payments are going to robosats.

**Comment by Reckless-Satoshi** [comment]
> Could be a good idea to recommend that users of custodial KYC wallets wrap robosats invoices before paying them so that their custodians are not able to figure out that payments are going to robosats.

One more reason for the built-in "Use lnproxy" form.
