### ISSUE TITLE
Add support for exact amount in advanced mode

### ISSUE THREAD

**Issue by stevenroose** [RoboSats/robosats#531]
Currently it's not possible to have an amount range from `XX EUR - XX EUR` where XX is thus a single amount, if you want to buy an exact amount. It needs to be a range.

Why is this? Why can't an exact amount be specified?

**Comment by Reckless-Satoshi** [comment]
Hey @stevenroose, thanks to bring up this issue.

There are two methods to indicate order amounts: the exact method and the range method. Ranges are constrained so the maximum has to be at least x1.5 of the minimum, but less than x8 (these constrains relate to the fact that makers always stake a bond size related to the max of the range). A range from X to X is not possible as it does not comply with the minimum range size, however, this fits the use of the exact amount method.

Since the last changes to the MakerForm, the amount method is tied to the Advanced Options switch. If you use Advanced options, you must have a range, and ranges must complain the requirements. This in fact, makes it impossible to use exact amount method in conjunction with custom timers. This something we should fix in the next releases. Probably a solution is to add a checkbox to decide whether a prince range is wanted in the Advanced Options view.

**Comment by stevenroose** [comment]
Ah yes I used advanced options to set the timers.

**Comment by JooVLC** [comment]
I started the development of the new feature. I'm still getting familiar with the project and the opensource community, sry for any mistake in the PR process.
