### ISSUE TITLE
Link does not work - Enable Telegram Notification

### ISSUE THREAD

**Issue by RealCocoArdo** [RoboSats/robosats#883]
**Describe the bug**
Enable Telegram Notification link doesnt work.

**To Reproduce**
1. Open Tor on your mobile Android
2. Open Robosats
3. Create or recover account
4. Click your Robotimage in the buttom left
5. Click the button Enable Telegram Notification
6.  Then there are the buttons to directly open the app by pressing enable or to open a link that opens a telegram webpage.
7. However they dont work.

**Expected behavior**
Telegram should be opend.

**Screenshots**
Seems unessary here.

**Smartphone :**
 - Device: Samsung Galaxy S6
 - OS: Android8.0
 - Browser TOR

**Additional context**
The buttons don't work on the mobile view. If I enable Desktop view inside Tor the buttons become functional again.

I tried it several times on diffrent days. Its consistent. I assume the tags have no href in the mobile version.

**Comment by Reckless-Satoshi** [comment]
Hey @RealCocoArdo thanks for bringing this up.

If using Tor Browser in Android, once you click "open in browser" and it takes you to the Telegram page, you should 1) click on the bottom right icon of the browser bar (three vertical dots) and then 2) "Open in App". Alternatively, you can click Enable or tap the QR code and it will ask you to select your Telegram client (if you have more than one) and directly open the chat. Both are tested to work on modern Android devices.

If the above is not true for your device, it might be due to the older Android version. It might be useful to find a way to use a newer OS version as we will not fix issues for Android versions that do not receive security updates anymore.

**Comment by RealCocoArdo** [comment]
Update.

The issue doesn't appear anymore.

No clue what happend. Weither you fixed or what. But I'm now also running Tor version 115.2.1-release(13.0) . Maybe that fixed the issue. But I can't tell for sure.  Just wanna let you know that everything is working now.

**Comment by Reckless-Satoshi** [comment]
> No clue what happend. Weither you fixed or what.

We did not fix anything, so this issue will remain a mystery :) Closing the issue.
