### ISSUE TITLE
Bond invoice is not popping up

### ISSUE THREAD

**Issue by Billybazzer** [RoboSats/robosats#949]
Accept offer, bond invoice does not appear and times out

**Expected behavior**
Usually, lightning invoice appears to lock offer

**Screenshots**
![image](https://github.com/RoboSats/robosats/assets/151049928/706de0fa-ec33-4065-9fe6-316196dd82b1)

**Desktop (please complete the following information):**
Ios and Linux

**Comment by Reckless-Satoshi** [comment]
Hey @Billybazzer this issue is related to the coordinator LND node being in a deadlock. It keeps happening sort of randomly and the coordinator becomes stuck until the node is restarted. As a user, the only way to proceed when this happens is to simply retry later.

Once the LND node is stuck the following user actions will not work:
- Making or taking orders (spinning wheel of death)
- Locking an invoice (never locks, order does not advance state)
- Confirm fiat received (spinning wheel of death)
- Submitting an invoice
- Cancelling an order (spinning wheel of death)

If any of these issues happen, you have to try back a few minutes later. Hopefully we figure a way to keep the LN node more stable, though it seems to be a hard task. 

We reported and tried to debug this issue here: https://github.com/lightningnetwork/lnd/issues/7917 
There were some implemented fixes that made the issue less frequent. But it seems LND will still enter deadlocks where `AddInvoice`, `LookupInvoice`, `SettleInvoice` and other methods timeout.

I will close this issue as there is nothing we can do to fix this problem in the RoboSats codebase. It falls on those operating RoboSats instances to deal with LN node stability.
